name: myapp
description: A exported flutter project from FUNCTION12

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  auto_route: ^7.8.4
  booking_calendar: ^1.1.10
  cloud_firestore: ^4.8.0
  cupertino_icons: ^1.0.2
  dropdown_button2: ^2.3.9
  easy_stepper: ^0.8.1
  equatable: ^2.0.5
  firebase_auth: ^4.12.1
  firebase_core: ^2.13.1
  firebase_storage: ^11.5.6
  firebase_ui_auth: ^1.9.1
  flutter:
    sdk: flutter
  flutter_mobx: ^2.2.0+1
  flutter_polyline_points: ^2.0.0
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.3.6
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  go_router: ^12.1.3
  google_fonts: ^4.0.4
  google_maps_flutter: ^2.5.0
  image_picker: ^1.0.4
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  kartal: ^3.5.0
  location: ^5.0.0
  logger: ^2.0.2+1
  mobx: ^2.3.0
  responsive_sizer: ^3.2.0
  shared_preferences: ^2.2.0

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.6.0

flutter:
  uses-material-design: true

  assets:
    - assets/rapidsport/images/
