name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  flutter_osm_plugin: ^0.60.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/rapidsport/images/home.png
    - assets/rapidsport/images/yesiltik.png
    - assets/rapidsport/images/besyildiz.png
    - assets/rapidsport/images/yuvarlaksag.png
    - assets/rapidsport/images/squash.png
    - assets/rapidsport/images/yuzme.png
    - assets/rapidsport/images/visainclogo-1.png
    - assets/rapidsport/images/duzenleme.png
    - assets/rapidsport/images/tenis.png
    - assets/rapidsport/images/weightlifting.png
    - assets/rapidsport/images/telefon.png
    - assets/rapidsport/images/kickboks.png
    - assets/rapidsport/images/mastercard-logo-1.png
    - assets/rapidsport/images/usericon.png
    - assets/rapidsport/images/boks.png
    - assets/rapidsport/images/ornekkullanici.png
    - assets/rapidsport/images/zumba.png
    - assets/rapidsport/images/map.png
    - assets/rapidsport/images/yoga.png
    - assets/rapidsport/images/dumbbell.png
    - assets/rapidsport/images/kirmizicarpi.png
    - assets/rapidsport/images/kosu.png
    - assets/rapidsport/images/pilates.png
    - assets/rapidsport/images/geriok.png
    - assets/rapidsport/images/minus.png
    - assets/rapidsport/images/giris1.png
    - assets/rapidsport/images/info.png
    - assets/rapidsport/images/plus.png
    - assets/rapidsport/images/egitmenikon.png
    - assets/rapidsport/images/location-pin.png
    - assets/rapidsport/images/buyutec.png
    - assets/rapidsport/images/kategoriarka.png
    - assets/rapidsport/images/avataryer.png
    - assets/rapidsport/images/yildizgri.png
    - assets/rapidsport/images/chevron-down.png
    - assets/rapidsport/images/kaloriarka.png
    - assets/rapidsport/images/programtarih.png
    - assets/rapidsport/images/bullet.png
    - assets/rapidsport/images/icon.png
    - assets/rapidsport/images/sagok.png
    - assets/rapidsport/images/giris3.png
    - assets/rapidsport/images/cikis.png
    - assets/rapidsport/images/botton-circle.png
    - assets/rapidsport/images/email.png
    - assets/rapidsport/images/bullet-CeH.png
    - assets/rapidsport/images/chevron-down-LDB.png
    - assets/rapidsport/images/giris2.png
    - assets/rapidsport/images/yildizsari.png
    - assets/rapidsport/images/mapiki.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
