// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA22-eW_FXc3PPxiQmlJljRJ1cJsqRZnOo',
    appId: '1:123094108738:web:cf6d9b106f5a713f067bdb',
    messagingSenderId: '123094108738',
    projectId: 'rapid-sportt',
    authDomain: 'rapid-sportt.firebaseapp.com',
    storageBucket: 'rapid-sportt.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCheOK9pI6EFyxL5ek4CSfnKdU0XBap9gw',
    appId: '1:123094108738:android:e4a266652c0118fd067bdb',
    messagingSenderId: '123094108738',
    projectId: 'rapid-sportt',
    storageBucket: 'rapid-sportt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQHWtQ13KPAC6KLjKx8gmL7zy7yZ-3G7w',
    appId: '1:123094108738:ios:e4e76d427cad5e70067bdb',
    messagingSenderId: '123094108738',
    projectId: 'rapid-sportt',
    storageBucket: 'rapid-sportt.appspot.com',
    iosBundleId: 'com.rapidsport.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQHWtQ13KPAC6KLjKx8gmL7zy7yZ-3G7w',
    appId: '1:123094108738:ios:17ea15217ed6248f067bdb',
    messagingSenderId: '123094108738',
    projectId: 'rapid-sportt',
    storageBucket: 'rapid-sportt.appspot.com',
    iosBundleId: 'com.example.test',
  );
}
