// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChGLT7jqd42LbTiTCUx9CMraVTrKmcD5U',
    appId: '1:723594552775:web:8bb171ad4cb3d79ee5a5e2',
    messagingSenderId: '723594552775',
    projectId: 'rapid-v1',
    authDomain: 'rapid-v1.firebaseapp.com',
    storageBucket: 'rapid-v1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA29EkEpLFDj11WNTLpUabg129U56eEmrI',
    appId: '1:723594552775:android:0e38127a5a28b239e5a5e2',
    messagingSenderId: '723594552775',
    projectId: 'rapid-v1',
    storageBucket: 'rapid-v1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPq0uObLAlGBZ5eUHSSBxeIhhsocm8enI',
    appId: '1:723594552775:ios:956d4ea387ab5348e5a5e2',
    messagingSenderId: '723594552775',
    projectId: 'rapid-v1',
    storageBucket: 'rapid-v1.appspot.com',
    iosBundleId: 'com.rapidsport.mchtsen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPq0uObLAlGBZ5eUHSSBxeIhhsocm8enI',
    appId: '1:723594552775:ios:cb39b4c73d5d501fe5a5e2',
    messagingSenderId: '723594552775',
    projectId: 'rapid-v1',
    storageBucket: 'rapid-v1.appspot.com',
    iosBundleId: 'com.example.test',
  );
}
